### ISSUE TITLE
Add  /.idea to .gitignore

### ISSUE THREAD

**Issue by ShGKme** [interlock/promise-policies#17]
/.idea directory should be ignored as it's user-depended and IDE-depended config.
Contributors, who use another IDE, don't need /.idea
Contributors, who use WebStorm, has their own /.idea

**Comment by interlock** [comment]
Sorry I missed this. I'll get a PR in to remove the existing .idea and ignore it

**Comment by interlock** [comment]
Addressed in commit b51bfe19baaee10df8c7b5f6c3dfd9fefa3552b7
